package uabc.ic.benjaminbolanos.practica2;

/**
 *
 * @author bbola
 */
public class InfoDialog extends javax.swing.JDialog {
    private boolean salidaExitosa;
    private final String figura;
    
    public InfoDialog(java.awt.Frame parent, boolean modal, String figura) {
        super(parent, modal);
        initComponents();
        this.figura = figura;
        setInfo();
        salidaExitosa = false;
    }
    
    /**
     * Método para cambiar las labels dependiendo de la figura.
     */
    private void setInfo(){
        //Se esconde el panel que contiene las labels especiales para espiral en caso de que sea necesario.
        panelEspiral.setVisible(false);
        labelFigura.setText(figura);
        switch(figura){
            case "Cuadrado" -> labelTam.setText("Tamaño del Lado:");
            case "Triangulo" -> labelTam.setText("Tamaño de Arista:");
            case "Espiral" -> {
                labelTam.setText("Ciclos:");
                panelEspiral.setVisible(true);
            }
            case "Circulo" -> labelTam.setText("Diametro:");
        }
    }
    
    /**
     * Método que retorna si hubo una salida exitosa (Info correcta para crear figura)
     * @return true si hay salida exitosa.
     */
    public boolean haySalidaExitosa(){
        return salidaExitosa && sonNumeros();
    }
    
    /**
     * Método para comprobar que todos los campos ingresados son digitos
     * @return true si la info ingresada es solo en dígitos
     */
    private boolean sonNumeros(){
        if(fieldX.getText().chars().allMatch(Character::isDigit) &&
            fieldY.getText().chars().allMatch(Character::isDigit) &&
            fieldTam.getText().chars().allMatch(Character::isDigit) &&
            !fieldX.getText().equals("") && !fieldY.getText().equals("") && !fieldTam.getText().equals(""))
        {
            if(figura.equals("Espiral") &&
                fieldRadioInicial.getText().chars().allMatch(Character::isDigit) &&
                fieldIncremento.getText().chars().allMatch(Character::isDigit) &&
                !fieldRadioInicial.getText().equals("") && !fieldIncremento.getText().equals(""))
            {
                return true;
            }
            if(!figura.equals("Espiral")){
                return true;
            }
        }
        return false;
    }
    
    /**
     * Método que retorna un array conteniendo toda la información de la figura a crear.
     * Si es espiral se retorna un array con capacidad de 5, en los demas casos
     * el array será de 3 espacios.
     * @return 
     */
    public int[] getInfo(){
        int capacidadArr;
        if(figura.equals("Espiral")) capacidadArr = 5;
        else capacidadArr = 3;
        int[] info = new int[capacidadArr];
        
        if(figura.equals("Espiral")){
            info[0] = Integer.parseInt(fieldX.getText());
            info[1] = Integer.parseInt(fieldY.getText());
            info[2] = Integer.parseInt(fieldTam.getText());
            info[3] = Integer.parseInt(fieldIncremento.getText());
            info[4] = Integer.parseInt(fieldRadioInicial.getText());
        } else {
            info[0] = Integer.parseInt(fieldX.getText());
            info[1] = Integer.parseInt(fieldY.getText());
            info[2] = Integer.parseInt(fieldTam.getText());
        }
        return info;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldX = new javax.swing.JTextField();
        fieldY = new javax.swing.JTextField();
        fieldTam = new javax.swing.JTextField();
        labelX = new javax.swing.JLabel();
        labelY = new javax.swing.JLabel();
        labelTam = new javax.swing.JLabel();
        aceptarBtn = new javax.swing.JButton();
        cancelarBtn = new javax.swing.JButton();
        panelEspiral = new javax.swing.JPanel();
        labelRadioInicial = new javax.swing.JLabel();
        fieldRadioInicial = new javax.swing.JTextField();
        fieldIncremento = new javax.swing.JTextField();
        labelIncremento = new javax.swing.JLabel();
        labelFigura = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingrese información de la figura:");
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);

        labelX.setText("Posicion en X:");

        labelY.setText("Posicion en Y:");

        labelTam.setText("Tamaño:");

        aceptarBtn.setText("Aceptar");
        aceptarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarBtnActionPerformed(evt);
            }
        });

        cancelarBtn.setText("Cancelar");
        cancelarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnActionPerformed(evt);
            }
        });

        labelRadioInicial.setText("Radio Inicial:");

        labelIncremento.setText("Incremento:");

        javax.swing.GroupLayout panelEspiralLayout = new javax.swing.GroupLayout(panelEspiral);
        panelEspiral.setLayout(panelEspiralLayout);
        panelEspiralLayout.setHorizontalGroup(
            panelEspiralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEspiralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelEspiralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelRadioInicial)
                    .addComponent(labelIncremento))
                .addGap(65, 65, 65)
                .addGroup(panelEspiralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fieldIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldRadioInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        panelEspiralLayout.setVerticalGroup(
            panelEspiralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEspiralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelEspiralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldRadioInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRadioInicial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelEspiralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldIncremento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIncremento))
                .addContainerGap())
        );

        labelFigura.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        labelFigura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFigura.setText("Figura");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 68, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelX)
                                    .addComponent(labelY)
                                    .addComponent(labelTam))
                                .addGap(65, 65, 65)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldTam, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldX, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldY, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(aceptarBtn)
                                .addGap(18, 18, 18)
                                .addComponent(cancelarBtn)
                                .addGap(115, 115, 115))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelFigura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelEspiral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelFigura, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelY))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldTam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTam))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelEspiral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarBtn)
                    .addComponent(cancelarBtn))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarBtnActionPerformed
        salidaExitosa = true;
        this.dispose();
    }//GEN-LAST:event_aceptarBtnActionPerformed

    private void cancelarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InfoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InfoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InfoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InfoDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(() -> {
            InfoDialog dialog = new InfoDialog(new javax.swing.JFrame(), true, "Figura");
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarBtn;
    private javax.swing.JButton cancelarBtn;
    private javax.swing.JTextField fieldIncremento;
    private javax.swing.JTextField fieldRadioInicial;
    private javax.swing.JTextField fieldTam;
    private javax.swing.JTextField fieldX;
    private javax.swing.JTextField fieldY;
    private javax.swing.JLabel labelFigura;
    private javax.swing.JLabel labelIncremento;
    private javax.swing.JLabel labelRadioInicial;
    private javax.swing.JLabel labelTam;
    private javax.swing.JLabel labelX;
    private javax.swing.JLabel labelY;
    private javax.swing.JPanel panelEspiral;
    // End of variables declaration//GEN-END:variables
}
