package uabc.ic.benjaminbolanos.practica2;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author bbola
 */
public class MainFrame extends javax.swing.JFrame {
    private boolean dibujandoPoligono;
    private final ArrayList<Integer> ptsPolX;
    private final ArrayList<Integer> ptsPolY;
    private int contadorLadosPol;
    
    public MainFrame() {
        initComponents();
        dibujandoPoligono = false;
        ptsPolX = new ArrayList();
        ptsPolY = new ArrayList();
        contadorLadosPol = 0;
    }
    
    /**
     * Método que limpia el canvas, pinta todas las figuras y actualiza el contador.
     */
    private void dibujarFiguras(){
        canvas.limpiar();
        canvas.dibujarFiguras(ordenTb.isSelected(),validarTb.isSelected(), cuadradosCb.isSelected(), 
                triangulosCb.isSelected(), espiralesCb.isSelected(), 
                circulosCb.isSelected(), poligonosCb.isSelected());
        actualizarContadorFiguras();
    }
    
    /**
     * Método para actualizar el label de contador de figuras.
     */
    private void actualizarContadorFiguras(){
        contadorLabel.setText("Figuras Creadas: " + canvas.cantidadFiguras());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotones = new javax.swing.JPanel();
        practicaLabel = new javax.swing.JLabel();
        cuadradoBtn = new javax.swing.JButton();
        trianguloBtn = new javax.swing.JButton();
        espiralBtn = new javax.swing.JButton();
        circuloBtn = new javax.swing.JButton();
        poligonoBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        dibujarBtn = new javax.swing.JButton();
        limpiarBtn = new javax.swing.JButton();
        eliminarBtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        contadorLabel = new javax.swing.JLabel();
        validarTb = new javax.swing.JToggleButton();
        canvas = new uabc.ic.benjaminbolanos.practica2.Canvas();
        jPanel1 = new javax.swing.JPanel();
        cuadradosCb = new javax.swing.JCheckBox();
        triangulosCb = new javax.swing.JCheckBox();
        espiralesCb = new javax.swing.JCheckBox();
        circulosCb = new javax.swing.JCheckBox();
        poligonosCb = new javax.swing.JCheckBox();
        ordenTb = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Practica 1 Bolaños Garrido");
        setLocationByPlatform(true);
        setResizable(false);

        panelBotones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        practicaLabel.setFont(new java.awt.Font("Impact", 0, 20)); // NOI18N
        practicaLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        practicaLabel.setText("Practica 1 Benjamin Bolaños");

        cuadradoBtn.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        cuadradoBtn.setText("Cuadrado");
        cuadradoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadradoBtnActionPerformed(evt);
            }
        });

        trianguloBtn.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        trianguloBtn.setText("Triangulo");
        trianguloBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trianguloBtnActionPerformed(evt);
            }
        });

        espiralBtn.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        espiralBtn.setText("Espiral");
        espiralBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                espiralBtnActionPerformed(evt);
            }
        });

        circuloBtn.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        circuloBtn.setText("Circulo");
        circuloBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circuloBtnActionPerformed(evt);
            }
        });

        poligonoBtn.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        poligonoBtn.setText("Poligono");
        poligonoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poligonoBtnActionPerformed(evt);
            }
        });

        dibujarBtn.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        dibujarBtn.setText("Dibujar Figuras");
        dibujarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dibujarBtnActionPerformed(evt);
            }
        });

        limpiarBtn.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        limpiarBtn.setText("Limpiar Canvas");
        limpiarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarBtnActionPerformed(evt);
            }
        });

        eliminarBtn.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        eliminarBtn.setText("Eliminar Figuras");
        eliminarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarBtnActionPerformed(evt);
            }
        });

        contadorLabel.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        contadorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contadorLabel.setText("Figuras Creadas: 0");

        validarTb.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        validarTb.setSelected(true);
        validarTb.setText("Validando");
        validarTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validarTbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonesLayout = new javax.swing.GroupLayout(panelBotones);
        panelBotones.setLayout(panelBotonesLayout);
        panelBotonesLayout.setHorizontalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(practicaLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                        .addGap(0, 58, Short.MAX_VALUE)
                        .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poligonoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(circuloBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(espiralBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(trianguloBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cuadradoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotonesLayout.createSequentialGroup()
                        .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(contadorLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())))
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(validarTb, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(eliminarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(limpiarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dibujarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelBotonesLayout.setVerticalGroup(
            panelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(practicaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuadradoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(trianguloBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(espiralBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(circuloBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(poligonoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(validarTb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dibujarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(limpiarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eliminarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contadorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        canvas.setBackground(new java.awt.Color(204, 204, 204));
        canvas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        canvas.setMaximumSize(new java.awt.Dimension(700, 550));
        canvas.setMinimumSize(new java.awt.Dimension(700, 550));
        canvas.setPreferredSize(new java.awt.Dimension(700, 542));
        canvas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canvasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout canvasLayout = new javax.swing.GroupLayout(canvas);
        canvas.setLayout(canvasLayout);
        canvasLayout.setHorizontalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        canvasLayout.setVerticalGroup(
            canvasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 548, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        cuadradosCb.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        cuadradosCb.setSelected(true);
        cuadradosCb.setText("Cuadrados");

        triangulosCb.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        triangulosCb.setSelected(true);
        triangulosCb.setText("Triangulos");

        espiralesCb.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        espiralesCb.setSelected(true);
        espiralesCb.setText("Espirales");

        circulosCb.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        circulosCb.setSelected(true);
        circulosCb.setText("Circulos");

        poligonosCb.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        poligonosCb.setSelected(true);
        poligonosCb.setText("Poligonos");

        ordenTb.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        ordenTb.setSelected(true);
        ordenTb.setText("Ascendente");
        ordenTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordenTbActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Impact", 0, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Orden de Dibujado");

        jLabel2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Seleccion de Figuras");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ordenTb, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cuadradosCb)
                        .addGap(5, 5, 5)
                        .addComponent(triangulosCb)
                        .addGap(5, 5, 5)
                        .addComponent(espiralesCb)
                        .addGap(5, 5, 5)
                        .addComponent(circulosCb)
                        .addGap(5, 5, 5)
                        .addComponent(poligonosCb))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ordenTb, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(circulosCb)
                            .addComponent(poligonosCb)
                            .addComponent(cuadradosCb)
                            .addComponent(triangulosCb)
                            .addComponent(espiralesCb))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(canvas, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(canvas, 550, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Evento para el boton Cuadrado. Abre un InfoDialog para Cuadrado.
     * En caso de salida exitosa, se crea la figura y se dibuja.
     * @param evt 
     */
    private void cuadradoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadradoBtnActionPerformed
        InfoDialog infoDialog = new InfoDialog(this,true, "Cuadrado");
        infoDialog.setVisible(true);
        if(infoDialog.haySalidaExitosa()){
            int[] infoFigura = infoDialog.getInfo();
            canvas.crearCuadrado(infoFigura[0], infoFigura[1], infoFigura[2]);
            dibujarFiguras();
        }
    }//GEN-LAST:event_cuadradoBtnActionPerformed

    /**
     * Evento para el boton Triangulo. Abre un InfoDialog para Triangulo.
     * En caso de salida exitosa, se crea la figura y se dibuja.
     * @param evt 
     */
    private void trianguloBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trianguloBtnActionPerformed
        InfoDialog infoDialog = new InfoDialog(this, true, "Triangulo");
        infoDialog.setVisible(true);
        if(infoDialog.haySalidaExitosa()){
            int[] infoFigura = infoDialog.getInfo();
            canvas.crearTriangulo(infoFigura[0], infoFigura[1], infoFigura[2]);
            dibujarFiguras();
        }
    }//GEN-LAST:event_trianguloBtnActionPerformed

    /**
     * Evento para el boton Espiral. Abre un InfoDialog para Espiral.
     * En caso de salida exitosa, se crea la figura y se dibuja.
     * @param evt 
     */
    private void espiralBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_espiralBtnActionPerformed
        InfoDialog infoDialog = new InfoDialog(this, true, "Espiral");
        infoDialog.setVisible(true);
        if(infoDialog.haySalidaExitosa()){
            int[] infoFigura = infoDialog.getInfo();
            canvas.crearEspiral(infoFigura[0], infoFigura[1], infoFigura[2], infoFigura[3], infoFigura[4]);
            dibujarFiguras();
        }
    }//GEN-LAST:event_espiralBtnActionPerformed

    /**
     * Evento para el boton Circulo. Abre un InfoDialog para Circulo.
     * En caso de salida exitosa, se crea la figura y se dibuja.
     * @param evt 
     */
    private void circuloBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circuloBtnActionPerformed
        InfoDialog infoDialog = new InfoDialog(this, true, "Circulo");
        infoDialog.setVisible(true);
        if(infoDialog.haySalidaExitosa()){
            int[] infoFigura = infoDialog.getInfo();
            canvas.crearCirculo(infoFigura[0], infoFigura[1], infoFigura[2]);
            dibujarFiguras();
        }
    }//GEN-LAST:event_circuloBtnActionPerformed

    /**
     * Evento para el boton Poligono. dibujandoPoligono se vuelve true
     * y se inhabilitan todos los botones para que sea entendible que se está 
     * dibujando un poligono.
     * @param evt 
     */
    private void poligonoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poligonoBtnActionPerformed
        dibujandoPoligono = true;
        for(Component c : panelBotones.getComponents()){
            c.setEnabled(false);
        }
    }//GEN-LAST:event_poligonoBtnActionPerformed

    /**
     * Evento de Mouse. Solo funciona si se está dibujando un poligono.
     * @param evt 
     */
    private void canvasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canvasMouseClicked
        if(dibujandoPoligono){
            //En caso de doble click
            if(evt.getClickCount() == 2){
                dibujandoPoligono = false;
                //Se eliminan el ultimo punto para no contar el punto al hacer doble click.
                ptsPolX.remove(ptsPolX.size()-1);
                ptsPolY.remove(ptsPolY.size()-1);
                //Si los lados del poligono son mayor que 1, el poligono se crea
                if(contadorLadosPol > 1) canvas.crearPoligono(ptsPolX, ptsPolY);
                //Se reinicia el contador de lados y los ArrayList
                contadorLadosPol = 0;
                ptsPolX.clear();
                ptsPolY.clear();
                //Se habilitan los demas botones
                for(Component c : panelBotones.getComponents())
                    c.setEnabled(true);
                //Se dibujan las figuras
                dibujarFiguras();
            
            //En caso de un click sencillo
            } else{
                //Se obtienen las posiciones en X y Y del Mouse.
                ptsPolX.add(evt.getX());
                ptsPolY.add(evt.getY());
                //Si se han dibujado mas de 0 lados, se dibujan lineas para ir visualizando la figura
                if(contadorLadosPol>0){
                    Graphics g=this.getGraphics();
                    g.setColor(Color.BLACK);
                    g.drawLine(ptsPolX.get(contadorLadosPol-1)+256, ptsPolY.get(contadorLadosPol-1)+30, ptsPolX.get(contadorLadosPol)+256, ptsPolY.get(contadorLadosPol)+30);
                }
                //Se aumenta el contador de lados.
                contadorLadosPol++;
            }
        }
    }//GEN-LAST:event_canvasMouseClicked

    /**
     * Evento para el boton Dibujar Figuras. Manda a dibujar las figuras.
     * @param evt 
     */
    private void dibujarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dibujarBtnActionPerformed
        dibujarFiguras();
    }//GEN-LAST:event_dibujarBtnActionPerformed

    /**
     * Evento para el boton Limpiar Canvas. Manda a limpiar el canvas y actualizar
     * el contador.
     * @param evt 
     */
    private void limpiarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarBtnActionPerformed
        canvas.limpiar();
        actualizarContadorFiguras();
    }//GEN-LAST:event_limpiarBtnActionPerformed

    /**
     * Evento para el boton Eliminar Figuras. Manda a eliminar todas las figuras,
     * limpiar el canvas y actualizar el contador.
     * @param evt 
     */
    private void eliminarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarBtnActionPerformed
        canvas.reiniciarFiguras();
        canvas.limpiar();
        actualizarContadorFiguras();
    }//GEN-LAST:event_eliminarBtnActionPerformed

    private void validarTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validarTbActionPerformed
        if(validarTb.isSelected()){
            validarTb.setText("Validando");
        } else {
            validarTb.setText("No Validando");
        }
        dibujarFiguras();
    }//GEN-LAST:event_validarTbActionPerformed

    private void ordenTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordenTbActionPerformed
        if(ordenTb.isSelected()){
            ordenTb.setText("Ascendente");
        } else {
            ordenTb.setText("Descendente");
        }
        dibujarFiguras();
    }//GEN-LAST:event_ordenTbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private uabc.ic.benjaminbolanos.practica2.Canvas canvas;
    private javax.swing.JButton circuloBtn;
    private javax.swing.JCheckBox circulosCb;
    private javax.swing.JLabel contadorLabel;
    private javax.swing.JButton cuadradoBtn;
    private javax.swing.JCheckBox cuadradosCb;
    private javax.swing.JButton dibujarBtn;
    private javax.swing.JButton eliminarBtn;
    private javax.swing.JButton espiralBtn;
    private javax.swing.JCheckBox espiralesCb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton limpiarBtn;
    private javax.swing.JToggleButton ordenTb;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JButton poligonoBtn;
    private javax.swing.JCheckBox poligonosCb;
    private javax.swing.JLabel practicaLabel;
    private javax.swing.JButton trianguloBtn;
    private javax.swing.JCheckBox triangulosCb;
    private javax.swing.JToggleButton validarTb;
    // End of variables declaration//GEN-END:variables
}
